# -*- coding: utf-8 -*-
"""TextBlob_Protagonist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fZPZNHCPV6F5ibBFxSFjBG30_advearS

# Display Top 10 Proper Nouns
"""

import string
import re

import nltk
nltk.download('brown')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

"""## Built on NLDK"""

from textblob import TextBlob

"""#### Opening the text book"""

text = open('/content/drive/My Drive/The secret of old  clock.txt')

"""#### Reading the text book"""

text= text.read()

text

type(text)

"""#### Storing the start and end of the book"""

a=text.find('Table of Contents')
b= text.find('she said with a broad smile')

a

b

"""Reading start to end of the book into a string"""

text=text[a:b]

text

"""#### Removing all the new line characters"""

text=text.replace('\n',' ')

"""#### Defining puntuations to be cleared"""

clearingSymbols = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~“’”'

for c in clearingSymbols:
  text=text.replace(c,'')

blob=TextBlob(text)

def top10words(bookBlob):
  d= bookBlob.np_counts
  d=dict(d)
  top10= sorted(d,key=d.get,reverse=True)
  return top10[:10]

verbs= ['VB','VBD','VBG','VBN','VBP','VBZ']

a= blob.tags

top10=top10words(blob)

proper_noun=['NNP','NNPS']

for word in top10:
  count =0
  for i in range(0,35314):
    if a[i][0] == word or a[i][0] == word.title():
      if a[i+1][1] in verbs and a[i][1] in proper_noun:
        count = count + 1
  if count / dictionary[word] >= 0.5:
    print(word)

